### ISSUE TITLE
not able to edit the blog entires

### ISSUE THREAD

**Issue by pendyalarajesh123** [Pylons/pyramid_blogr#63] opened 2017-02-15 13:50 UTC
Hi,

I am able to create entries in DB, but when i tried to edit the entries, getting the error " ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]**Cannot update identity column 'id'.** (8102) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)") [SQL: u'UPDATE entries SET id=?, body=? WHERE entries.id = ?'] [parameters: (u'7', u'for testing in pyramid framework', 7)]".

Please some one help me on this.

**Comment by ergo** [comment] 2017-02-15 15:12
I'm affraid I never used MSSQL.

It looks like there a type mismatch for ID? Why are you trying to update the pkey in the first place?

**Comment by pendyalarajesh123** [comment] 2017-02-16 08:45
i am not updating the pkey, when i tried to update the title and blog content, it is redirecting and trying to update the ID which is the primary key. 
I took the source code from here and changed the sqlalchemy.url in development.ini file.

**Comment by ergo** [comment] 2017-02-16 09:36
Ok,

I think I know the cause - I will update the example soon.

**Comment by pendyalarajesh123** [comment] 2017-02-16 10:34
Thanks in advance.

**Comment by pendyalarajesh123** [comment] 2017-02-28 07:36
Hi ergo,
can you please give some updates on the above issue?

**Comment by ergo** [comment] 2017-02-28 08:58
@pendyalarajesh123 

I think the reason this happens is that here:

https://github.com/Pylons/pyramid_blogr/blob/master/pyramid_blogr/views/blog.py#L39

the form tries to use:
https://github.com/Pylons/pyramid_blogr/blob/master/pyramid_blogr/forms.py#L13

the 'id' from the form is used as string - you can try changing `BlogUpdateForm` to `BlogCreateForm` in the view and this should fix the issue for you.

I'll update the tutorial (along with 1.8 changes) when I find the time.

**Comment by pendyalarajesh123** [comment] 2017-02-28 12:46
Hi ergo, thanks for the information.

I changed the view blog.py in #line 39 as 
"form = BlogCreateForm(request.POST, entry)", still I am getting the below error.

"UndefinedError: 'pyramid_blogr.forms.BlogCreateForm object' has no attribute 'id'"

**Comment by ergo** [comment] 2017-02-28 12:48
@pendyalarajesh123 please do https://docs.python.org/3/tutorial/ first to understand the basics of python programming, you should have much easier time to follow the tutorial.

**Comment by pendyalarajesh123** [comment] 2017-02-28 12:59
Thanks for the info.

**Comment by ergo** [comment] 2017-09-24 11:15
Should be fixed in latest version of tutorial

**Closed by ergo** 2017-09-24 11:15 UTC
